# Generated by Django 6.0.6 on 2026-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Self Employed', 'Self Employed')], max_length=50)),
                ('salary_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('DAT', 'DAT')], max_length=20)),
                ('credit_score', models.PositiveIntegerField()),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], default='Not Eligible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
