# Generated by Django 6.0.6 on 2026-07-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_directory', '0002_eligibilityresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='eligibility_status',
        ),
    ]
