# Generated by Django 6.0.6 on 2026-07-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=100)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('min_credit_score', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Self Employed', 'Self Employed')], max_length=50)),
                ('salary_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('DAT', 'DAT')], max_length=20)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
